name: Test Project
on: 
  push:
jobs:
  test:
    runs-on: ubuntu:latest
    steps:
      - name: check out the code
        uses: action/checkout@v3
      - name: install the nodeJS
        uses: action/setup-node@v3
      - name: install the required dependencies
        run: npm install
      - name: testing the code
        run: npm test
      - name: telling hai
        run: |
             echo"delated happy birthday anuhya"
             echo"where is the party"
        

